encyclopedia/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("entry/<str:title>/", views.entry_page, name="entry_page"),
    path("wiki/<str:title>/", views.entry_page, name="entry_page"),
    path("search/", views.search, name="search"),
    path("new_page/<str:title>", views.new_page, name="new_page"),
    path("new_page/", views.create_entry, name="new_page"),
    path('edit/<str:title>/', views.edit_entry, name='edit_entry'),
    path("random/", views.random_entry, name="random_entry"),
    path("about_page/", views.about_page, name="about_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class EntryForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    content = forms.CharField(label='Content', widget=forms.Textarea)

encyclopedia/views.py
import markdown2
import random

from django import forms
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse

from . import util, forms
from .forms import EntryForm
def index(request):
    
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()
    })
    
def about_page(request):
    
    return render(request, "encyclopedia/about_page.html")

# Render an entry when clicked
def entry_page(request, title):
    content = util.get_entry(title)
    if content is None:
        raise Http404("Entry not found")
    
    entry_html = markdown2.markdown(content)
    return render(request, "encyclopedia/entry_page.html",{
        "title": title,
        "content": entry_html,
    })

# Search for typed entry
def search(request):
    query = request.GET.get('q','')
    if query:
        entries = util.list_entries()
        # Dont understand how this works. edit: apparently it's called 'list comprehension'
        matching_entries = [entry for entry in entries if query.lower() in entry.lower()] 
        if len(matching_entries) == 1 and matching_entries[0].lower == query.lower():
            # Redirect to the entry page if there's an exact match
            return redirect('entry_page', title=matching_entries[0])
        else:
            return render(request, "encyclopedia/search_results.html", {
                "query": query,
                "entries": matching_entries,
            })
    else:
        return redirect('index')
    

# Making new entry (kinda broken, dont touch!)
def new_page(request,title):
    context = {
        'title': 'new_page',
        'message': "Welcome to the new page!"
    }
    return render(request, 'encyclopedia/new_page.html', context)

# Making new entry
def create_entry(request):
    # Links to forms.py
    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            util.save_entry(title, content)
            return redirect('index')
    else:
        form = EntryForm()
    return render(request, 'encyclopedia/new_page.html', {'forms': form})

# Edit existing entry
def edit_entry(request, title):
    if request.method == 'POST':
        #existing_content = util.get_entry(title)
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title, content)
        return redirect('index')
    
    else:
        existing_content = util.get_entry(title)
        if existing_content:
            initial_data = {
                'title': title,
                'content': existing_content,                
            }
            form = EntryForm(initial = initial_data)
            return render(request, 'encyclopedia/edit_entry.html',{
                'form': form,
            })
        else:
            raise Http404("Entry not found")

# Randomly direct to existing entry       
def random_entry(request):
    # Be advised, these are not using random.choice
    entries = util.list_entries()
    entry_number_map = {}
    number = 1
    entries_number = len(entries)
    
    # Assigning entries with numbers in a dictionary
    for entry in entries:
        entry_number_map[entry] = number
        number += 1

    # Randomizing the value to get the key
    random_int = random.randint(1, entries_number) 
    random_entry_title = entries[random_int - 1]
    return redirect('entry_page', title=random_entry_title)

encyclopedia/templates/encyclopedia/about_page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block extra_css %}
        <link href="{% static 'encyclopedia/about_page.css' %}" rel="stylesheet">  <!-- Specific CSS for new_page.html -->
    {% endblock %}

{% block title %} 
    About
{% endblock %}

{% block body %}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1>About CS50W Project 1: Wiki</h1>
        <hr>
        <br>

        <h2>Project Description</h2>
        <hr>
        <p>This project is a simple wiki website by <a href="//github.com/AyKaay"><b>Farrel A</a></b> built as part of Harvard's CS50W Web Programming with Python and JavaScript course made by. 
            The site allows users to create, edit, and view encyclopedia entries written in Markdown.</p>
        <br>

        <h2>Features</h2>
        <hr>
        <ul>
            <li><strong>View Entries</strong>: Users can view a list of all encyclopedia entries.</li>
            <li><strong>View Entry</strong>: Users can click on an entry to view its content.</li>
            <li><strong>Search</strong>: Users can search for an entry by its title or content. Partial matches are also displayed.</li>
            <li><strong>Create New Entry</strong>: Users can create a new encyclopedia entry.</li>
            <li><strong>Edit Entry</strong>: Users can edit existing encyclopedia entries.</li>
            <li><strong>Random Entry</strong>: Users can view a random encyclopedia entry.</li>
            <li><strong>Markdown Support</strong>: Entries are written in Markdown and rendered as HTML.</li>
        </ul>
        <br>

        <h2>Technologies Used</h2>
        <hr>
        <ul>
            <li><strong>Backend</strong>: Django, Python</li>
            <li><strong>Frontend</strong>: HTML, CSS, Bootstrap</li>
            <li><strong>Markdown</strong>: Python-Markdown for rendering Markdown content</li>
        </ul>
        <br>

        <h2>Usage</h2>
        <hr>
        <ol>
            <li><strong>View Entries</strong>: Navigate to the home page to see a list of all encyclopedia entries.</li>
            <li><strong>Search Entries</strong>: Use the search bar to find entries by title or content.</li>
            <li><strong>Create New Entry</strong>: Click on "Create New Page" to add a new entry.</li>
            <li><strong>Edit Entry</strong>: Open an entry and click "Edit" to modify its content.</li>
            <li><strong>Random Entry</strong>: Click on "Random Page" to view a random entry.</li>
        </ol>
        <br>

        <h2>Project Structure</h2>
        <hr>
        <ul>
            <li><code>encyclopedia/</code>: Contains the main application code.
            <ul>
                    <li><code>migrations/</code>: Database migrations.</li>
                    <li><code>static/</code>: Static files (CSS).</li>
                    <li><code>templates/</code>: HTML templates.</li>
                    <li><code>models.py</code>: Database models.</li>
                    <li><code>views.py</code>: Application views.</li>
                    <li><code>urls.py</code>: URL routing.</li>
                </ul>
            </li>
            <li><code>wiki/</code>: Project settings and configurations.
                <ul>
                    <li><code>settings.py</code>: Project settings.</li>
                    <li><code>urls.py</code>: Project URL routing.</li>
                    <li><code>util.py</code>: Project encyclopedia query utilities.</li>
                </ul>
            </li>
        </ul>
        <br>

        <h2>Acknowledgements</h2>
        <hr>
        <p>The project is part of the <a href="https://cs50.harvard.edu/web/2020/">CS50W Web Programming with Python and JavaScript</a> course by Harvard University.</p>
        <br>
    </div>

{% endblock %} 

encyclopedia/templates/encyclopedia/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Edit</title>
</head>
<body>
    <h1>Editing:  {{ form.title.value }}</h1>
    <form method="post">
    {% csrf_token %}
    <br>
    {{form.as_p}}
    <input type="submit"></button>
    </form>
    <a href="{% url 'index' %}">Back to index</a>
</body>
</html> 

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'encyclopedia/entry_page.css' %}" rel="stylesheet">  <!-- Specific CSS for new_page.html -->
{% endblock %}

{% block title %} 
    {{title}}
{% endblock %}

{% block body %}
    <div class="main col-lg-10 col-md-9">
    <hr>
        {{ content|safe }}
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'encyclopedia/index.css' %}" rel="stylesheet">  <!-- Specific CSS for new_page.html -->
{% endblock %}

{% block title %} 
    Main Menu
{% endblock %}

{% block body %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1>Welcome to Our Wikipedia Mock-up</h1> 
    <hr>
    <br>

    <h2> About This Project </h2>
    <hr>
    <p>
        This Wikipedia mock-up is a project created as part of Harvard's CS50W course. 
        The goal of this project is to provide a platform for learning and sharing knowledge on various topics, much like the real Wikipedia.
        Here, users can create, edit, and browse articles on a wide range of subjects,
         from programming languages to historical figures, and everything in between.
    </p>
    <br>

    <h2>Features</h2>
    <hr>
    <ul class="intro-text">
        <li><b>Comprehensive Articles: </b>Our platform hosts detailed articles on various topics, providing users with in-depth knowledge.</li>
        <li><b>User Contributions: </b>Anyone can contribute by creating new articles or editing existing ones, fostering a collaborative learning environment.</li>
        <li><b>Search Functionality: </b>Easily find articles using our intuitive search bar.</li>
        <li><b>Random Article: </b>Explore something new with a click by viewing a random article.</li>
    </ul>
    <br>

    <h2>Why This Project?</h2>
    <hr>
    <p>
        Inspired by the structure and functionality of Wikipedia, 
        this project serves as an educational tool to understand the workings of a content management system (CMS) and web development.
         It showcases the application of Django, HTML, CSS, and providing hands-on experience in building and managing web applications.
    </p>
    <br>

    <h2>Get Involved</h2>
    <hr>
    <p>
        We encourage you to dive in and explore the articles available.
         If you have knowledge to share, feel free to contribute by creating new pages or improving existing content.
         Your contributions help make this a valuable resource for everyone.
    <p>
    <br>
    <!--
        <ul>
            {% for entry in entries %}  
            <li><a href="{% url 'entry_page' title=entry %}">{{entry}}</a></li>  
            {% endfor %} 
        </ul>  
    </div>
    -->
{% endblock %} 

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>  
<html lang="en">  
    <head>
        {% block extra_css %}{% endblock %}  <!-- Additional CSS specific to each page -->
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">  <!-- Bootstrap CSS for styling -->
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="container-fluid">
        <div class="row"> 
        <div class="col-sm-3 col-md-2 sidebar"> 
            <h2><b><a href="{% url 'index' %}">Wikipedia Mock-up</a></b></h2>
            <p>Harvard CS50W based Project<p>
            <!-- search bar functionalities-->
            <form action="{% url 'search' %}" method="get"> 
                <input class="form-control form-control-sm" type="text" name="q" placeholder="Search Wikipedia">  
                <button type="submit" class="btn btn-secondary btn-sm">Search</button>
            </form>
            <hr>
            <!-- Navigation links -->
            <nav class="sidebar_nav">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'new_page' %}">Create New Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'random_entry' %}">Random Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about_page' %}">About</a>
                    </li>
                </ul>
            </nav>

            <!-- Sidebar footer -->
            <footer class="sidebar_footer">
                
                <p>&copy; 2024 Wikipedia Mock-up</p>
                <a href="https://github.com/AyKaay">More by Me!</a>
                <a href="https://github.com/me50/AyKaay/blob/web50/projects/2020/x/wiki/README.md"> Code: Under the hood </a>
            </footer>

        </div>

        <!-- Main content section taking 10 columns on large screens and 9 on medium screens -->
        <div class="main col-lg-10 col-md-9">  
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>  <!-- End of the HTML document -->

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'encyclopedia/new_page.css' %}" rel="stylesheet">  <!-- Specific CSS for new_page.html -->
{% endblock %}

{% block title %} 
    Create New Wiki
{% endblock %}

{% block body %}
    <div class="main col-lg-10 col-md-9">
        <form method="post">
            <!--Page Title-->
            <h1>Create a New Wiki Entry</h1>
            <hr>
            <p>We are absolutely delighted to have you here!
                Your contribution is incredibly valuable to us and the entire community.
                By sharing your knowledge, experiences, and insights, you help build a richer, more diverse resource for everyone.
                We believe that every entry you create can make a difference and provide meaningful information to our users.
            </p>
            <p>You can write your content using 
                <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">Markdown2 format</a>
                , which allows you to easily format your text, create lists, add links,
                    and include other elements such as code snippets or block quotes.
                If you have any questions or need assistance, please reach out to our support team at farrelatalla141@gmail.com.
                    We're here to help!
            </p>
            <br>
            
            <!-- Introduction text-->
            <h2> Getting Started</h2>
            <hr>
            <p><b>Title: </b> Provide a concise and descriptive title for your entry. This will help others understand the main topic at a glance.</p>
            <b>Content: </b> Write detailed content for your entry. Be as informative as possible and include any relevant details that would help readers.</p>
            
            <hr>
            <!--Page Content-->
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label><br>
                {{ forms.title }}
            </div>
            <div class="form-group">
                <label for="id_content">Content:</label><br>
                {{ forms.content }}
            </div>
            <input type="submit" class="btn btn-primary" value="Save Entry">
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
<!DOCTYPE html>
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'encyclopedia/search_result.css' %}" rel="stylesheet">  <!-- Specific CSS for new_page.html -->
{% endblock %}

{% block title %} 
    Search Result
{% endblock %}

{% block body %}
    <div class="main col-lg-10 col-md-9">
        <h1>Search result for "{{ query }}"</h1>
        <hr>
        <ul>
            {% if entries %}
                {% for entry in entries %}
                    <li><a href="{% url 'entry_page' entry%}"><b>{{entry}}</b></a></li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
{% endblock %}